name: Build Windows - OTX Server  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: windows-latest  
      
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
        
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v2  
        
    - name: Setup vcpkg  
      run: |  
        git clone https://github.com/Microsoft/vcpkg.git  
        .\vcpkg\bootstrap-vcpkg.bat  
        echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $GITHUB_ENV  
          
    - name: Install dependencies  
      run: |  
        .\vcpkg\vcpkg.exe install boost:x64-windows libxml2:x64-windows sqlite3:x64-windows openssl:x64-windows lua:x64-windows mysql-connector-cpp:x64-windows libiconv:x64-windows mpir:x64-windows  
          
    - name: Build x64 Release  
      run: msbuild sources/msvc/TheOTXServer.vcxproj /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0.22621.0  
        
    - name: Upload artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: otx-server-windows  
        path: sources/msvc/x64/Release/
